import { Inter } from "next/font/google";
import "./globals.css";
import axios from "axios";

var token = 'c06e1a9e4fdc04e962527e901a50dd20eed895094b88d56cd20399d33a3eac5143a4cde97a7e0c6ffd213f1316fe9bdb0a67a905f2a0451bf0dccb5af0592d3c746f27aae1ab730c145eb2a5375d7e8cfbd3c8c2d856120fd7a9b0794f06870f60d8e510cea4e2b15aaa286c5d022e61028924becf4fd377b26d4aeea18cd97e';
/*
axios.get("http://localhost:1337/api/images/1?populate[0]=Image", {
  headers: {
    'Authorization' : 'Bearer ' + token
  }
}).then((res) => {
   const resHttp = res.data;
console.log(resHttp.data.attributes.Image.data[0].attributes.name);

});*/


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
